# Generated by Django 3.2.3 on 2021-07-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='gender',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='password',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
