# Generated by Django 3.2.3 on 2021-08-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0006_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='image',
            field=models.ImageField(default=123, upload_to='image/'),
            preserve_default=False,
        ),
    ]
