# Generated by Django 3.2.3 on 2021-08-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0008_auto_20210804_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sort_term_memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stm_picture/')),
            ],
        ),
    ]
