# Generated by Django 3.0.1 on 2021-08-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0012_sort_term_memory_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sort_term_memory',
            name='number',
            field=models.IntegerField(),
        ),
    ]
