# Generated by Django 3.0.1 on 2021-08-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0013_auto_20210818_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='store_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=100)),
                ('ans', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
