# Generated by Django 3.0.1 on 2021-08-31 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0016_choice_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
