# Generated by Django 3.0.1 on 2021-08-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0017_auto_20210831_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=30)),
                ('two', models.CharField(max_length=30)),
                ('three', models.CharField(max_length=30)),
                ('four', models.CharField(max_length=30)),
                ('five', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
