# Generated by Django 3.0.1 on 2021-08-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0018_gamedata_gameuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameUser',
        ),
    ]
