# Generated by Django 3.0.1 on 2021-09-08 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0020_auto_20210831_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedata',
            name='username',
        ),
        migrations.RenameModel(
            old_name='GameName',
            new_name='UserName',
        ),
        migrations.CreateModel(
            name='GameMod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mod', models.CharField(max_length=30)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.UserName')),
            ],
        ),
        migrations.AddField(
            model_name='gamedata',
            name='mod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='robot.GameMod'),
            preserve_default=False,
        ),
    ]
