# Generated by Django 3.0.1 on 2021-09-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0021_auto_20210908_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='five',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='four',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='one',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='three',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='two',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='TimeStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_one', models.CharField(max_length=30)),
                ('time_two', models.CharField(max_length=30)),
                ('time_three', models.CharField(max_length=30)),
                ('time_four', models.CharField(max_length=30)),
                ('time_five', models.CharField(max_length=30)),
                ('game_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.GameData')),
            ],
        ),
    ]
