# Generated by Django 3.0.1 on 2021-09-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0022_auto_20210908_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='five',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='four',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='one',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='three',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='two',
            field=models.CharField(max_length=30),
        ),
    ]
