# Generated by Django 3.0.1 on 2021-09-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0024_auto_20210908_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='date',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
